matrixnorm::hadoop_head_node: matrixnorm1.docker
hadoop::hadoop_storage_dirs:
  - /data/1
  - /data/2
hadoop_cluster_node::cluster_components:
  - hdfs 
  - yarn
  - mapreduce
matrixnorm::matrixnorm_repo_uri: docker.io/vslovik/puppet

