docker:
        memory_limit: "4g"
        image: "vslovik/puppet:centos-7" // "bigtop/puppet:centos-7"

repo: "http://bigtop-repos.s3.amazonaws.com/releases/1.2.0/centos/7/x86_64"
distro: centos
components: [hdfs, yarn, mapreduce]
enable_local_repo: false
smoke_test_components: [hdfs, yarn, mapreduce]