matrixnorm:
    image: ${DOCKER_IMAGE}
    command: /sbin/init
    domainname: org.unipi.matrixnorm
    privileged: true
    mem_limit: ${MEM_LIMIT}
    volumes:
    - ../../:/matrixnorm-home
    - ./config/hiera.yaml:/etc/puppet/hiera.yaml
    - ./config/hieradata:/etc/puppet/hieradata
    - ./config/hosts:/etc/hosts